export const WARD_OPTIONS = [
  { value: "", label: "Phường/Xã" },
  { value: "phuong-an-dong", label: "Phường An Đông" },
  { value: "phuong-an-hoi-dong", label: "Phường An Hội Đông" },
  { value: "phuong-an-hoi-tay", label: "Phường An Hội Tây" },
  { value: "phuong-an-khanh", label: "Phường An Khánh" },
  { value: "phuong-an-lac", label: "Phường An Lạc" },
  { value: "phuong-an-nhon", label: "Phường An Nhơn" },
  { value: "phuong-an-phu", label: "Phường An Phú" },
  { value: "phuong-an-phu-dong", label: "Phường An Phú Đông" },
  { value: "phuong-ba-ria", label: "Phường Bà Rịa" },
  { value: "phuong-ban-co", label: "Phường Bàn Cờ" },
  { value: "phuong-bay-hien", label: "Phường Bảy Hiền" },
  { value: "phuong-ben-cat", label: "Phường Bến Cát" },
  { value: "phuong-ben-thanh", label: "Phường Bến Thành" },
  { value: "phuong-binh-co", label: "Phường Bình Cơ" },
  { value: "phuong-binh-duong", label: "Phường Bình Dương" },
  { value: "phuong-binh-dong", label: "Phường Bình Đông" },
  { value: "phuong-binh-hoa", label: "Phường Bình Hòa" },
  { value: "phuong-binh-hung-hoa", label: "Phường Bình Hưng Hòa" },
  { value: "phuong-binh-loi-trung", label: "Phường Bình Lợi Trung" },
  { value: "phuong-binh-phu", label: "Phường Bình Phú" },
  { value: "phuong-binh-quoi", label: "Phường Bình Quới" },
  { value: "phuong-binh-tan", label: "Phường Bình Tân" },
  { value: "phuong-binh-tay", label: "Phường Bình Tây" },
  { value: "phuong-binh-thanh", label: "Phường Bình Thạnh" },
  { value: "phuong-binh-thoi", label: "Phường Bình Thới" },
  { value: "phuong-binh-tien", label: "Phường Bình Tiên" },
  { value: "phuong-binh-tri-dong", label: "Phường Bình Trị Đông" },
  { value: "phuong-binh-trung", label: "Phường Bình Trưng" },
  { value: "phuong-cat-lai", label: "Phường Cát Lái" },
  { value: "phuong-cau-kieu", label: "Phường Cầu Kiệu" },
  { value: "phuong-cau-ong-lanh", label: "Phường Cầu Ông Lãnh" },
  { value: "phuong-chanh-hiep", label: "Phường Chánh Hiệp" },
  { value: "phuong-chanh-hung", label: "Phường Chánh Hưng" },
  { value: "phuong-chanh-phu-hoa", label: "Phường Chánh Phú Hòa" },
  { value: "phuong-cho-lon", label: "Phường Chợ Lớn" },
  { value: "phuong-cho-quan", label: "Phường Chợ Quán" },
  { value: "phuong-di-an", label: "Phường Dĩ An" },
  { value: "phuong-dien-hong", label: "Phường Diên Hồng" },
  { value: "phuong-dong-hoa", label: "Phường Đông Hòa" },
  { value: "phuong-dong-hung-thuan", label: "Phường Đông Hưng Thuận" },
  { value: "phuong-duc-nhuan", label: "Phường Đức Nhuận" },
  { value: "phuong-gia-dinh", label: "Phường Gia Định" },
  { value: "phuong-go-vap", label: "Phường Gò Vấp" },
  { value: "phuong-hanh-thong", label: "Phường Hạnh Thông" },
  { value: "phuong-hiep-binh", label: "Phường Hiệp Bình" },
  { value: "phuong-hoa-binh", label: "Phường Hòa Bình" },
  { value: "phuong-hoa-hung", label: "Phường Hòa Hưng" },
  { value: "phuong-hoa-loi", label: "Phường Hòa Lợi" },
  { value: "phuong-khanh-hoi", label: "Phường Khánh Hội" },
  { value: "phuong-lai-thieu", label: "Phường Lái Thiêu" },
  { value: "phuong-linh-xuan", label: "Phường Linh Xuân" },
  { value: "phuong-long-binh", label: "Phường Long Bình" },
  { value: "phuong-long-huong", label: "Phường Long Hương" },
  { value: "phuong-long-nguyen", label: "Phường Long Nguyên" },
  { value: "phuong-long-phuoc", label: "Phường Long Phước" },
  { value: "phuong-long-truong", label: "Phường Long Trường" },
  { value: "phuong-minh-phung", label: "Phường Minh Phụng" },
  { value: "phuong-nhieu-loc", label: "Phường Nhiêu Lộc" },
  { value: "phuong-phu-an", label: "Phường Phú An" },
  { value: "phuong-phu-dinh", label: "Phường Phú Định" },
  { value: "phuong-phu-lam", label: "Phường Phú Lâm" },
  { value: "phuong-phu-loi", label: "Phường Phú Lợi" },
  { value: "phuong-phu-my", label: "Phường Phú Mỹ" },
  { value: "phuong-phu-nhuan", label: "Phường Phú Nhuận" },
  { value: "phuong-phu-thanh", label: "Phường Phú Thạnh" },
  { value: "phuong-phu-tho", label: "Phường Phú Thọ" },
  { value: "phuong-phu-tho-hoa", label: "Phường Phú Thọ Hòa" },
  { value: "phuong-phu-thuan", label: "Phường Phú Thuận" },
  { value: "phuong-phuoc-long", label: "Phường Phước Long" },
  { value: "phuong-phuoc-thang", label: "Phường Phước Thắng" },
  { value: "phuong-rach-dua", label: "Phường Rạch Dừa" },
  { value: "phuong-sai-gon", label: "Phường Sài Gòn" },
  { value: "phuong-tam-binh", label: "Phường Tam Bình" },
  { value: "phuong-tam-long", label: "Phường Tam Long" },
  { value: "phuong-tam-thang", label: "Phường Tam Thắng" },
  { value: "phuong-tang-nhon-phu", label: "Phường Tăng Nhơn Phú" },
  { value: "phuong-tan-binh", label: "Phường Tân Bình" },
  { value: "phuong-tan-dinh", label: "Phường Tân Định" },
  { value: "phuong-tan-dong-hiep", label: "Phường Tân Đông Hiệp" },
  { value: "phuong-tan-hai", label: "Phường Tân Hải" },
  { value: "phuong-tan-hiep", label: "Phường Tân Hiệp" },
  { value: "phuong-tan-hoa", label: "Phường Tân Hòa" },
  { value: "phuong-tan-hung", label: "Phường Tân Hưng" },
  { value: "phuong-tan-khanh", label: "Phường Tân Khánh" },
  { value: "phuong-tan-my", label: "Phường Tân Mỹ" },
  { value: "phuong-tan-phu", label: "Phường Tân Phú" },
  { value: "phuong-tan-phuoc", label: "Phường Tân Phước" },
  { value: "phuong-tan-son", label: "Phường Tân Sơn" },
  { value: "phuong-tan-son-hoa", label: "Phường Tân Sơn Hòa" },
  { value: "phuong-tan-son-nhat", label: "Phường Tân Sơn Nhất" },
  { value: "phuong-tan-son-nhi", label: "Phường Tân Sơn Nhì" },
  { value: "phuong-tan-tao", label: "Phường Tân Tạo" },
  { value: "phuong-tan-thanh", label: "Phường Tân Thành" },
  { value: "phuong-tan-thoi-hiep", label: "Phường Tân Thới Hiệp" },
  { value: "phuong-tan-thuan", label: "Phường Tân Thuận" },
  { value: "phuong-tan-uyen", label: "Phường Tân Uyên" },
  { value: "phuong-tay-nam", label: "Phường Tây Nam" },
  { value: "phuong-tay-thanh", label: "Phường Tây Thạnh" },
  { value: "phuong-thanh-my-tay", label: "Phường Thạnh Mỹ Tây" },
  { value: "phuong-thong-tay-hoi", label: "Phường Thông Tây Hội" },
  { value: "phuong-thoi-an", label: "Phường Thới An" },
  {
    value: "phuong-thoi-hoa",
    label: "Phường Thới An (không sáp nhập, giữ nguyên)",
  },
  { value: "phuong-thu-dau-mot", label: "Phường Thủ Dầu Một" },
  { value: "phuong-thu-duc", label: "Phường Thủ Đức" },
  { value: "phuong-thuan-an", label: "Phường Thuận An" },
  { value: "phuong-thuan-giao", label: "Phường Thuận Giao" },
  { value: "phuong-trung-my-tay", label: "Phường Trung Mỹ Tây" },
  { value: "phuong-vinh-hoi", label: "Phường Vĩnh Hội" },
  { value: "phuong-vinh-tan", label: "Phường Vĩnh Tân" },
  { value: "phuong-vung-tau", label: "Phường Vũng Tàu" },
  { value: "phuong-vuon-lai", label: "Phường Vườn Lài" },
  { value: "phuong-xom-chieu", label: "Phường Xóm Chiếu" },
  { value: "phuong-xuan-hoa", label: "Phường Xuân Hòa" },

  // --- XÃ ---
  { value: "xa-an-long", label: "Xã An Long" },
  { value: "xa-an-nhon-tay", label: "Xã An Nhơn Tây" },
  { value: "xa-an-thoi-dong", label: "Xã An Thới Đông" },
  { value: "xa-ba-diem", label: "Xã Bà Điểm" },
  { value: "xa-bau-bang", label: "Xã Bàu Bàng" },
  { value: "xa-bau-lam", label: "Xã Bàu Lâm" },
  { value: "xa-bac-tan-uyen", label: "Xã Bắc Tân Uyên" },
  { value: "xa-binh-chanh", label: "Xã Bình Chánh" },
  { value: "xa-binh-chau", label: "Xã Bình Châu (không sáp nhập, giữ nguyên)" },
  { value: "xa-binh-gia", label: "Xã Bình Giã" },
  { value: "xa-binh-hung", label: "Xã Bình Hưng" },
  { value: "xa-binh-khanh", label: "Xã Bình Khánh" },
  { value: "xa-binh-loi", label: "Xã Bình Lợi" },
  { value: "xa-binh-my", label: "Xã Bình Mỹ" },
  { value: "xa-can-gio", label: "Xã Cần Giờ" },
  { value: "xa-chau-duc", label: "Xã Châu Đức" },
  { value: "xa-chau-pha", label: "Xã Châu Pha" },
  { value: "xa-cu-chi", label: "Xã Củ Chi" },
  { value: "xa-dau-tieng", label: "Xã Dầu Tiếng" },
  { value: "xa-dat-do", label: "Xã Đất Đỏ" },
  { value: "xa-dong-thanh", label: "Xã Đông Thạnh" },
  { value: "xa-hiep-phuoc", label: "Xã Hiệp Phước" },
  { value: "xa-hoa-hiep", label: "Xã Hòa Hiệp (không sáp nhập, giữ nguyên)" },
  { value: "xa-hoa-hoi", label: "Xã Hòa Hội" },
  { value: "xa-hoc-mon", label: "Xã Hóc Môn" },
  { value: "xa-ho-tram", label: "Xã Hồ Tràm" },
  { value: "xa-hung-long", label: "Xã Hưng Long" },
  { value: "xa-kim-long", label: "Xã Kim Long" },
  { value: "xa-long-dien", label: "Xã Long Điền" },
  { value: "xa-long-hai", label: "Xã Long Hải" },
  { value: "xa-long-hoa", label: "Xã Long Hòa" },
  { value: "xa-long-son", label: "Xã Long Sơn (không sáp nhập, giữ nguyên)" },
  { value: "xa-minh-thanh", label: "Xã Minh Thạnh" },
  { value: "xa-ngai-giao", label: "Xã Ngãi Giao" },
  { value: "xa-nghia-thanh", label: "Xã Nghĩa Thành" },
  { value: "xa-nha-be", label: "Xã Nhà Bè" },
  { value: "xa-nhuan-duc", label: "Xã Nhuận Đức" },
  { value: "xa-phu-giao", label: "Xã Phú Giáo" },
  { value: "xa-phu-hoa-dong", label: "Xã Phú Hòa Đông" },
  { value: "xa-phuoc-hai", label: "Xã Phước Hải" },
  { value: "xa-phuoc-hoa", label: "Xã Phước Hòa" },
  { value: "xa-phuoc-thanh", label: "Xã Phước Thành" },
  { value: "xa-tan-an-hoi", label: "Xã Tân An Hội" },
  { value: "xa-tan-nhut", label: "Xã Tân Nhựt" },
  { value: "xa-tan-vinh-loc", label: "Xã Tân Vĩnh Lộc" },
  { value: "xa-thai-my", label: "Xã Thái Mỹ" },
  { value: "xa-thanh-an", label: "Xã Thanh An" },
  {
    value: "xa-thanh-an-cg",
    label: "Xã Thạnh An (không sáp nhập, giữ nguyên)",
  },
  { value: "xa-thuong-tan", label: "Xã Thường Tân" },
  { value: "xa-tru-van-tho", label: "Xã Trừ Văn Thố" },
  { value: "xa-vinh-loc", label: "Xã Vĩnh Lộc" },
  { value: "xa-xuan-son", label: "Xã Xuân Sơn" },
  { value: "xa-xuan-thoi-son", label: "Xã Xuân Thới Sơn" },
  { value: "xa-xuyen-moc", label: "Xã Xuyên Mộc" },
];
